default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV['DB_POOL'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 3306

development:
  <<: *default
  database: zalo_bot_development

test:
  <<: *default
  database: zalo_bot_test

production:
  <<: *default
  database: zalo_bot_production
  username: zalo_bot
  password: <%= ENV['ZALO_BOT_DATABASE_PASSWORD'] %>
